authservice:
  jwtSecret:  "your-256-bit-secret"
  jwtExpirationMs: 3600000

spring:
  application:
    name: AuthService


server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


